### ISSUE TITLE
Weekly scrum – 08/03/2023

### ISSUE THREAD

**Issue by H-Jallad** [H-Jallad/SYSC4806-Perk_Manager-Group20#1]

**Comment by H-Jallad** [comment]
Things I have done:

- #5 
- #4 
- #13 

Things I will be doing:

- #33 
- #31 
- #30

**Comment by areebhaq14** [comment]
Things I have done: 
https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/6 Create CI Workflow
https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/15 Create Controllers
https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/18 Create Views for Memberships
https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/21 Create Views for Perks

Things I will be doing:
https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/26 Create Login capabilities for user

**Comment by raj1034** [comment]
Things I have done:

- https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/23
- https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/20
- https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/19
- https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/15
- https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/2

Things I will be doing:

- https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/28
- https://github.com/H-Jallad/SYSC4806-Perk_Manager-Group20/issues/29

**Comment by santhosh808** [comment]
Things I have done:
#3 
#9 

Things I will be doing:
#30 
#40 
#41

**Comment by mutazaldisi** [comment]
Things I have Done:
- added Tests for Membership
- Added Tests for Perk
- Added Tests for Person
- Added web Mock MVC tests

Things I will be doing:
- more testing
- UI enhancement
